[project]
name = "OffSeasonPractice"
version = "1.0"
requires-python = ">=3.13,<3.14"
dependencies = [
    "robotpy[navx,rev,phoenix6,pathplannerlib]==2025.3.2.2",
    "photonlibpy",
]


[tool.uv]
python-preference = "managed"

#
# Use this configuration file to control what RobotPy packages are installed
# on your RoboRIO
#

[tool.robotpy]

# Version of robotpy this project depends on
robotpy_version = "2025.3.2.2"

# Which extra RobotPy components should be installed
# -> equivalent to `pip install robotpy[extra1, ...]
robotpy_extras = ["navx", "rev", "phoenix6", "pathplannerlib"]

# Other pip packages to install
requires = ["numpy", "photonlibpy"]